<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 4.4.10 setup script
 * Date: Sat, 27 Jun 2015 18:43:17 +0200
 */

/* Servers configuration */
$i = 0;

/* Server: Win [1] */
$i++;
$cfg['Servers'][$i]['verbose'] = 'Win';
$cfg['Servers'][$i]['host'] = 'localhost';
$cfg['Servers'][$i]['port'] = '';
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['connect_type'] = 'tcp';
$cfg['Servers'][$i]['auth_type'] = 'cookie';
$cfg['Servers'][$i]['user'] = 'root';
$cfg['Servers'][$i]['password'] = '';

/* End of servers configuration */

$cfg['blowfish_secret'] = '558ed1cec2d883.59497505';
$cfg['DefaultLang'] = 'en';
$cfg['ServerDefault'] = 1;
$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';
?>